spring.datasource.url=jdbc:postgresql://switchback.proxy.rlwy.net:16689/railway
spring.datasource.username=postgres
spring.datasource.password=dUasrBtnqjvpKbHpflotavxeHKjiHsod
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect